site_name: Knowledge Hub
site_url: https://knowledgehub.ldt4ssc.eu/

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png   # Add your logo in docs/assets/logo.png
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    # Do not enable toc.integrate â†’ removes right TOC
  palette:
    - scheme: default
      primary: white
      accent: amber
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  favicon: assets/fav_icon_resized.png

nav:
  - Welcome: index.md
  - Strategy & Sustainability: strategy.md
  - Smart Communities Ecosystem: communities.md
  - Pilot Guidance: guidance.md
  - Resources for Pilots: resources.md
  - Pilot Journey: journey.md


    
markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - toc:
      permalink: false
 # disables table of contents panel
    
extra_css:
  - assets/extra.css
  - css/resources_poc.css
  - css/methodology_diagram.css
  - css/feedback_widget.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.snippets # allows embedding external content
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
  generator: false  # hide "Made with Material for MkDocs"
  homepage: https://ldt4ssc.eu/ # logo links back to project home, instead of KH home

extra_javascript:
#  - js/footer.js
  - js/logo-top-redirect.js # script to avoid the frameset loop in the project website
  - js/frame-escape.js # script to escape the frame for all external links
  - js/resources_poc.js # test resource interactive frame



copyright: LDT4SSC is a project funded by the Digital Europe Programme under grant agreement number 101226211. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Commission. Neither the European Union nor the European Commission can be held responsible for them.

